name: Deploy para GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: production
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v4

      - name: Substituir arquivo de configuração
        run: |
          echo "Reescrevendo assets/js/config.js com API_BASE_URL do ambiente..."
          mkdir -p assets/js
          cat > assets/js/config.js <<EOF
          const CONFIG = {
            API_BASE_URL: '${{ vars.API_BASE_URL }}',
            LOGIN_REDIRECT: 'login.html'
          };
          EOF

      - name: Verificar conteúdo (debug opcional)
        run: |
          echo "Conteúdo atual do config.js:"
          cat assets/js/config.js

      - name: Configurar GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload dos arquivos
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Fazer deploy
        id: deployment
        uses: actions/deploy-pages@v4
